In [67]:
import cv2
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import time
import mediapipe as mp

### Các bộ phân được tách
head 0

shoulder 11, 12

elbow 13, 14

wrist 15, 16

hip 23, 24

knee 25, 26

ankle 27, 28

In [68]:
video_path = "test.mp4"
model_path = "pose_landmarker_lite.task"

In [69]:
KEYPOINTS = [0, 11, 12, 13, 14, 15, 16, 23, 24, 25, 26, 27, 28]

BODY_PARTS = {
    'head':     [0],
    'shoulder': [11, 12],
    'elbow':    [13, 14],
    'wrist':    [15, 16],
    'hip':      [23, 24],
    'knee':     [25, 26],
    'ankle':    [27, 28],
}

GROUP = {
    0: 'head',
    11: 'left shoulder', 12: 'right shoulder',
    13: 'left elbow', 14: 'right elbow',
    15: 'left wrist', 16: 'right wrist',
    23: 'left hip', 24: 'right hip',
    25: 'left knee', 26: 'right knee',
    27: 'left ankle', 28: 'right ankle'
}

In [70]:
BaseOptions = mp.tasks.BaseOptions
PoseLandmarker = mp.tasks.vision.PoseLandmarker
PoseLandmarkerOptions = mp.tasks.vision.PoseLandmarkerOptions
VisionRunningMode = mp.tasks.vision.RunningMode

base_options = PoseLandmarkerOptions(
    base_options=BaseOptions(model_asset_path=model_path),
    running_mode=VisionRunningMode.VIDEO,
    num_poses=1)


cap = cv2.VideoCapture(video_path)
fps = cap.get(cv2.CAP_PROP_FPS)

def draw_landmarks(frame, result):
    if not result.pose_landmarks:
        return frame
    
    frame_copy = frame.copy()
    (h, w) = frame_copy.shape[:2]

    point_color = (0, 0, 255)

    KEYPOINTS = [0, 11, 12, 13, 14, 15, 16, 23, 24, 25, 26, 27, 28]

    for idx in KEYPOINTS:
        landmark = result.pose_landmarks[0][idx]

        if landmark.presence < 0.5 or landmark.visibility < 0.5:
            continue
        
        px = int(landmark.x * w)
        py = int(landmark.y * h)

        cv2.circle(frame_copy, (px, py), 6, point_color, -1)

    return frame_copy

extracted_data = []
def extract_data(result, frame_idx):
    if not result.pose_world_landmarks:
        return
    
    data = result.pose_world_landmarks[0]

    for landmark_id, landmark in enumerate(data):
        if landmark_id not in KEYPOINTS:
            continue

        extracted_data.append({
            'frame': frame_idx,
            'part': GROUP[landmark_id],
            'part_idx': landmark_id,
            'x': landmark.x,
            'y': landmark.y,
            'z': landmark.z,
            'visibility': landmark.visibility,
            'presence': landmark.presence
        })



with PoseLandmarker.create_from_options(base_options) as landmarker:
    frame_idx = 0
    rows = []

    while cap.isOpened():
        ret, frame = cap.read()

        if not ret:
            break

        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
        
        rgb_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

        timestamp_ms = int((frame_idx / fps) * 1000)
        image = mp.Image(image_format=mp.ImageFormat.SRGB, data=rgb_frame)

        result = landmarker.detect_for_video(image, timestamp_ms)

        if result.pose_landmarks:
            for landmark_id, landmark in enumerate(result.pose_landmarks[0]):
                if landmark.presence > 0.5 and landmark.visibility > 0.5:
                    print(f"Frame {frame_idx} | Landmark #{landmark_id}\nx={landmark.x:.3f}\ny={landmark.y:.3f}\nz={landmark.z:.3f}\nvisibility={landmark.visibility}\npresence={landmark.presence}")
        
        drawed_frame = draw_landmarks(frame, result)

        cv2.imshow("Camera", drawed_frame)
        
        extract_data(result, frame_idx)
        
        frame_idx += 1

cap.release()
cv2.destroyAllWindows()

Frame 0 | Landmark #0
x=0.386
y=0.613
z=-1.910
visibility=0.999153733253479
presence=0.9992303848266602
Frame 0 | Landmark #1
x=0.435
y=0.563
z=-1.733
visibility=0.999256432056427
presence=0.9989808201789856
Frame 0 | Landmark #2
x=0.461
y=0.565
z=-1.732
visibility=0.9991770386695862
presence=0.9987483024597168
Frame 0 | Landmark #3
x=0.486
y=0.567
z=-1.731
visibility=0.999071478843689
presence=0.9983447790145874
Frame 0 | Landmark #4
x=0.345
y=0.555
z=-1.845
visibility=0.9993681311607361
presence=0.9992930889129639
Frame 0 | Landmark #5
x=0.304
y=0.551
z=-1.846
visibility=0.9993483424186707
presence=0.9993194341659546
Frame 0 | Landmark #6
x=0.266
y=0.546
z=-1.846
visibility=0.9993675351142883
presence=0.9992745518684387
Frame 0 | Landmark #7
x=0.505
y=0.582
z=-0.744
visibility=0.9982261061668396
presence=0.9978456497192383
Frame 0 | Landmark #8
x=0.192
y=0.551
z=-1.246
visibility=0.9993707537651062
presence=0.9992493987083435
Frame 0 | Landmark #9
x=0.415
y=0.664
z=-1.529
visibility=0.9981324076652527
presence=0.9963800311088562
Frame 0 | Landmark #10
x=0.307
y=0.658
z=-1.677
visibility=0.9988394379615784
presence=0.9981539845466614
Frame 0 | Landmark #11
x=0.579
y=0.808
z=-0.130
visibility=0.9870153665542603
presence=0.9563193917274475
Frame 0 | Landmark #12
x=-0.051
y=0.820
z=-0.940
visibility=0.9908973574638367
presence=0.9774591326713562
Frame 0 | Landmark #17
x=0.465
y=0.814
z=-1.646
visibility=0.6896417737007141
presence=0.5684788227081299
Frame 0 | Landmark #19
x=0.472
y=0.797
z=-1.645
visibility=0.6859495043754578
presence=0.6315619349479675
Frame 0 | Landmark #21
x=0.448
y=0.780
z=-1.462
visibility=0.7255331873893738
presence=0.5950376987457275
Frame 1 | Landmark #0
x=0.387
y=0.611
z=-1.830
visibility=0.9991762638092041
presence=0.9993054866790771
Frame 1 | Landmark #1
x=0.435
y=0.563
z=-1.652
visibility=0.9992600679397583
presence=0.9990770816802979
Frame 1 | Landmark #2
x=0.461
y=0.565
z=-1.652
visibility=0.9991889595985413
presence=0.9989625215530396
Frame 1 | Landmark #3
x=0.486
y=0.567
z=-1.651
visibility=0.9990835785865784
presence=0.9987485408782959
Frame 1 | Landmark #4
x=0.345
y=0.553
z=-1.778
visibility=0.9993607997894287
presence=0.9992175102233887
Frame 1 | Landmark #5
x=0.305
y=0.548
z=-1.778
visibility=0.9993414282798767
presence=0.9991937279701233
Frame 1 | Landmark #6
x=0.267
y=0.543
z=-1.778
visibility=0.9993481636047363
presence=0.9990580677986145
Frame 1 | Landmark #7
x=0.504
y=0.582
z=-0.682
visibility=0.9982820749282837
presence=0.9985709190368652
Frame 1 | Landmark #8
x=0.192
y=0.550
z=-1.245
visibility=0.9993529319763184
presence=0.9989602565765381
Frame 1 | Landmark #9
x=0.415
y=0.656
z=-1.460
visibility=0.9982388615608215
presence=0.9985664486885071
Frame 1 | Landmark #10
x=0.308
y=0.651
z=-1.629
visibility=0.9988921284675598
presence=0.9990382194519043
Frame 1 | Landmark #11
x=0.579
y=0.808
z=-0.049
visibility=0.9878110289573669
presence=0.9840747117996216
Frame 1 | Landmark #12
x=-0.054
y=0.820
z=-1.041
visibility=0.991330087184906
presence=0.9860602617263794
Frame 2 | Landmark #0
x=0.386
y=0.603
z=-1.799
visibility=0.9991405606269836
presence=0.9984906911849976
Frame 2 | Landmark #1
x=0.433
y=0.557
z=-1.616
visibility=0.9992238879203796
presence=0.9982057809829712
Frame 2 | Landmark #2
x=0.460
y=0.560
z=-1.615
visibility=0.9991562366485596
presence=0.9979598522186279
Frame 2 | Landmark #3
x=0.485
y=0.562
z=-1.615
visibility=0.9990538954734802
presence=0.9975278973579407
Frame 2 | Landmark #4
x=0.344
y=0.546
z=-1.746
visibility=0.9993091821670532
presence=0.9984645843505859
Frame 2 | Landmark #5
x=0.305
y=0.541
z=-1.746
visibility=0.999284565448761
presence=0.9984116554260254
Frame 2 | Landmark #6
x=0.267
y=0.536
z=-1.746
visibility=0.9992825984954834
presence=0.9981756210327148
Frame 2 | Landmark #7
x=0.502
y=0.577
z=-0.624
visibility=0.9982547163963318
presence=0.9970641732215881
Frame 2 | Landmark #8
x=0.191
y=0.544
z=-1.219
visibility=0.9992775917053223
presence=0.9978796243667603
Frame 2 | Landmark #9
x=0.415
y=0.646
z=-1.420
visibility=0.9981998205184937
presence=0.9948076605796814
Frame 2 | Landmark #10
x=0.308
y=0.642
z=-1.595
visibility=0.9988305568695068
presence=0.9964157342910767
Frame 2 | Landmark #11
x=0.576
y=0.806
z=0.017
visibility=0.9878076910972595
presence=0.9505363702774048
Frame 2 | Landmark #12
x=-0.059
y=0.815
z=-1.028
visibility=0.9908669590950012
presence=0.9538851380348206
Frame 3 | Landmark #0
x=0.384
y=0.593
z=-1.815
visibility=0.9991863369941711
presence=0.9991112351417542
Frame 3 | Landmark #1
x=0.430
y=0.546
z=-1.631
visibility=0.9992729425430298
presence=0.9990150928497314
Frame 3 | Landmark #2
x=0.457
y=0.550
z=-1.631
visibility=0.9992092251777649
presence=0.9988835453987122
Frame 3 | Landmark #3
x=0.482
y=0.553
z=-1.630
visibility=0.9991137981414795
presence=0.9986172914505005
Frame 3 | Landmark #4
x=0.342
y=0.534
z=-1.759
visibility=0.9993457794189453
presence=0.999047577381134
Frame 3 | Landmark #5
x=0.303
y=0.530
z=-1.760
visibility=0.9993175864219666
presence=0.9989539384841919
Frame 3 | Landmark #6
x=0.265
y=0.525
z=-1.760
visibility=0.9993125200271606
presence=0.9987221360206604
Frame 3 | Landmark #7
x=0.496
y=0.568
z=-0.594
visibility=0.998380184173584
presence=0.9984523057937622
Frame 3 | Landmark #8
x=0.188
y=0.535
z=-1.209
visibility=0.99930739402771
presence=0.9984169006347656
Frame 3 | Landmark #9
x=0.414
y=0.635
z=-1.427
visibility=0.9982300996780396
presence=0.993065357208252
Frame 3 | Landmark #10
x=0.307
y=0.632
z=-1.603
visibility=0.9988218545913696
presence=0.9943764209747314
Frame 3 | Landmark #11
x=0.558
y=0.794
z=0.082
visibility=0.9864644408226013
presence=0.8988268375396729
Frame 3 | Landmark #12
x=-0.059
y=0.808
z=-1.032
visibility=0.9892444014549255
presence=0.9109941124916077
Frame 4 | Landmark #0
x=0.381
y=0.584
z=-1.838
visibility=0.999114453792572
presence=0.9969727993011475
Frame 4 | Landmark #1
x=0.426
y=0.539
z=-1.654
visibility=0.9992268085479736
presence=0.996992826461792
Frame 4 | Landmark #2
x=0.453
y=0.543
z=-1.654
visibility=0.9991644024848938
presence=0.996625542640686
Frame 4 | Landmark #3
x=0.478
y=0.546
z=-1.655
visibility=0.9990666508674622
presence=0.9959656000137329
Frame 4 | Landmark #4
x=0.338
y=0.526
z=-1.792
visibility=0.9992858171463013
presence=0.9972720742225647
Frame 4 | Landmark #5
x=0.301
y=0.520
z=-1.793
visibility=0.9992486238479614
presence=0.9971038699150085
Frame 4 | Landmark #6
x=0.264
y=0.515
z=-1.793
visibility=0.9992345571517944
presence=0.9966021776199341
Frame 4 | Landmark #7
x=0.487
y=0.561
z=-0.606
visibility=0.998367190361023
presence=0.9953802824020386
Frame 4 | Landmark #8
x=0.186
y=0.524
z=-1.249
visibility=0.9992427229881287
presence=0.9959403276443481
Frame 4 | Landmark #9
x=0.410
y=0.626
z=-1.432
visibility=0.9980968832969666
presence=0.9853305816650391
Frame 4 | Landmark #10
x=0.304
y=0.622
z=-1.623
visibility=0.9986962080001831
presence=0.989173412322998
Frame 4 | Landmark #11
x=0.553
y=0.788
z=0.042
visibility=0.9848237037658691
presence=0.8372507095336914
Frame 4 | Landmark #12
x=-0.072
y=0.796
z=-1.067
visibility=0.987433671951294
presence=0.8601048588752747
Frame 5 | Landmark #0
x=0.378
y=0.577
z=-1.684
visibility=0.9990906715393066
presence=0.9986549615859985
Frame 5 | Landmark #1
x=0.421
y=0.532
z=-1.511
visibility=0.9992197751998901
presence=0.9987837672233582
Frame 5 | Landmark #2
x=0.448
y=0.536
z=-1.511
visibility=0.999161422252655
presence=0.9987483024597168
Frame 5 | Landmark #3
x=0.473
y=0.538
z=-1.511
visibility=0.9990701675415039
presence=0.9986492991447449
Frame 5 | Landmark #4
x=0.334
y=0.519
z=-1.651
visibility=0.999248743057251
presence=0.9985952973365784
Frame 5 | Landmark #5
x=0.297
y=0.513
z=-1.652
visibility=0.9991950988769531
presence=0.9983548521995544
Frame 5 | Landmark #6
x=0.260
y=0.507
z=-1.651
visibility=0.9991628527641296
presence=0.997871994972229
Frame 5 | Landmark #7
x=0.476
y=0.553
z=-0.535
visibility=0.9984133243560791
presence=0.9986300468444824
Frame 5 | Landmark #8
x=0.184
y=0.516
z=-1.193
visibility=0.9991714358329773
presence=0.9970421195030212
Frame 5 | Landmark #9
x=0.404
y=0.617
z=-1.303
visibility=0.9980947971343994
presence=0.9945604205131531
Frame 5 | Landmark #10
x=0.301
y=0.613
z=-1.495
visibility=0.9986435770988464
presence=0.995020866394043
Frame 5 | Landmark #11
x=0.531
y=0.779
z=0.090
visibility=0.984835147857666
presence=0.9470954537391663
Frame 5 | Landmark #12
x=-0.082
y=0.788
z=-1.062
visibility=0.9858113527297974
presence=0.8999327421188354
Frame 6 | Landmark #0
x=0.373
y=0.563
z=-1.722
visibility=0.9990813732147217
presence=0.9990645051002502
Frame 6 | Landmark #1
x=0.413
y=0.518
z=-1.542
visibility=0.9992026686668396
presence=0.999065101146698
Frame 6 | Landmark #2
x=0.440
y=0.521
z=-1.542
visibility=0.9991545677185059
presence=0.9989909529685974
Frame 6 | Landmark #3
x=0.465
y=0.523
z=-1.542
visibility=0.9990590810775757
presence=0.9988610744476318
Frame 6 | Landmark #4
x=0.325
y=0.507
z=-1.669
visibility=0.9992242455482483
presence=0.9991180300712585
Frame 6 | Landmark #5
x=0.287
y=0.501
z=-1.670
visibility=0.9991715550422668
presence=0.9990583062171936
Frame 6 | Landmark #6
x=0.249
y=0.496
z=-1.670
visibility=0.9991248250007629
presence=0.9988798499107361
Frame 6 | Landmark #7
x=0.466
y=0.539
z=-0.549
visibility=0.9984411597251892
presence=0.9987868666648865
Frame 6 | Landmark #8
x=0.176
y=0.505
z=-1.238
visibility=0.9991458654403687
presence=0.9986811280250549
Frame 6 | Landmark #9
x=0.400
y=0.606
z=-1.328
visibility=0.9981760382652283
presence=0.997893750667572
Frame 6 | Landmark #10
x=0.296
y=0.602
z=-1.498
visibility=0.99869304895401
presence=0.9984519481658936
Frame 6 | Landmark #11
x=0.533
y=0.776
z=0.062
visibility=0.9856327772140503
presence=0.9753798246383667
Frame 6 | Landmark #12
x=-0.110
y=0.788
z=-1.117
visibility=0.9863728284835815
presence=0.9756104350090027
Frame 7 | Landmark #0
x=0.368
y=0.555
z=-1.740
visibility=0.9989815950393677
presence=0.9968854784965515
Frame 7 | Landmark #1
x=0.407
y=0.510
z=-1.565
visibility=0.9991282820701599
presence=0.9969931840896606
Frame 7 | Landmark #2
x=0.434
y=0.513
z=-1.564
visibility=0.9990807175636292
presence=0.9966962337493896
Frame 7 | Landmark #3
x=0.459
y=0.515
z=-1.563
visibility=0.998982846736908
presence=0.9961585402488708
Frame 7 | Landmark #4
x=0.318
y=0.497
z=-1.686
visibility=0.9991344809532166
presence=0.9971856474876404
Frame 7 | Landmark #5
x=0.281
y=0.492
z=-1.687
visibility=0.9990755319595337
presence=0.9970170259475708
Frame 7 | Landmark #6
x=0.242
y=0.486
z=-1.687
visibility=0.9990112781524658
presence=0.9965102076530457
Frame 7 | Landmark #7
x=0.457
y=0.531
z=-0.575
visibility=0.9983951449394226
presence=0.9956879019737244
Frame 7 | Landmark #8
x=0.169
y=0.494
z=-1.273
visibility=0.9990492463111877
presence=0.9957612156867981
Frame 7 | Landmark #9
x=0.394
y=0.598
z=-1.359
visibility=0.9980705380439758
presence=0.9884907007217407
Frame 7 | Landmark #10
x=0.290
y=0.594
z=-1.511
visibility=0.998581051826477
presence=0.9908682107925415
Frame 7 | Landmark #11
x=0.513
y=0.772
z=0.090
visibility=0.9844043254852295
presence=0.8878074884414673
Frame 7 | Landmark #12
x=-0.120
y=0.777
z=-1.153
visibility=0.9852176308631897
presence=0.8808603882789612
Frame 8 | Landmark #0
x=0.362
y=0.546
z=-1.831
visibility=0.9989990592002869
presence=0.9985523819923401
Frame 8 | Landmark #1
x=0.401
y=0.501
z=-1.646
visibility=0.9991350769996643
presence=0.9983471632003784
Frame 8 | Landmark #2
x=0.428
y=0.504
z=-1.645
visibility=0.9990876317024231
presence=0.9980712532997131
Frame 8 | Landmark #3
x=0.454
y=0.507
z=-1.645
visibility=0.9989854693412781
presence=0.9976089000701904
Frame 8 | Landmark #4
x=0.311
y=0.488
z=-1.796
visibility=0.9991507530212402
presence=0.9987518787384033
Frame 8 | Landmark #5
x=0.272
y=0.481
z=-1.797
visibility=0.9990984201431274
presence=0.9987695813179016
Frame 8 | Landmark #6
x=0.233
y=0.475
z=-1.796
visibility=0.9990344047546387
presence=0.9986380934715271
Frame 8 | Landmark #7
x=0.451
y=0.523
z=-0.602
visibility=0.9984375238418579
presence=0.9970410466194153
Frame 8 | Landmark #8
x=0.161
y=0.483
z=-1.337
visibility=0.9990841150283813
presence=0.9984948635101318
Frame 8 | Landmark #9
x=0.388
y=0.591
z=-1.425
visibility=0.9981331825256348
presence=0.9941613078117371
Frame 8 | Landmark #10
x=0.283
y=0.585
z=-1.622
visibility=0.9986354112625122
presence=0.9966248273849487
Frame 8 | Landmark #11
x=0.509
y=0.767
z=0.082
visibility=0.9839175939559937
presence=0.9066729545593262
Frame 8 | Landmark #12
x=-0.136
y=0.770
z=-1.185
visibility=0.9855924844741821
presence=0.954095721244812
Frame 9 | Landmark #0
x=0.355
y=0.542
z=-1.902
visibility=0.9989528059959412
presence=0.9974236488342285
Frame 9 | Landmark #1
x=0.394
y=0.496
z=-1.719
visibility=0.9990928173065186
presence=0.9973914623260498
Frame 9 | Landmark #2
x=0.422
y=0.500
z=-1.718
visibility=0.9990482926368713
presence=0.9971253275871277
Frame 9 | Landmark #3
x=0.448
y=0.503
z=-1.718
visibility=0.9989461898803711
presence=0.9966058731079102
Frame 9 | Landmark #4
x=0.304
y=0.483
z=-1.873
visibility=0.9991034269332886
presence=0.9976673722267151
Frame 9 | Landmark #5
x=0.265
y=0.476
z=-1.874
visibility=0.9990525841712952
presence=0.9976215958595276
Frame 9 | Landmark #6
x=0.226
y=0.469
z=-1.874
visibility=0.9989818334579468
presence=0.9972969889640808
Frame 9 | Landmark #7
x=0.445
y=0.518
z=-0.676
visibility=0.9984273910522461
presence=0.9961909055709839
Frame 9 | Landmark #8
x=0.155
y=0.477
z=-1.396
visibility=0.999037504196167
presence=0.996894121170044
Frame 9 | Landmark #9
x=0.380
y=0.588
z=-1.497
visibility=0.9981227517127991
presence=0.991979718208313
Frame 9 | Landmark #10
x=0.272
y=0.582
z=-1.703
visibility=0.998603105545044
presence=0.9940192699432373
Frame 9 | Landmark #11
x=0.502
y=0.759
z=0.021
visibility=0.9839684367179871
presence=0.9326180219650269
Frame 9 | Landmark #12
x=-0.149
y=0.759
z=-1.237
visibility=0.985729992389679
presence=0.9466205835342407
Frame 10 | Landmark #0
x=0.348
y=0.537
z=-1.898
visibility=0.9988723397254944
presence=0.9970799088478088
Frame 10 | Landmark #1
x=0.388
y=0.492
z=-1.714
visibility=0.9989994764328003
presence=0.9968991279602051
Frame 10 | Landmark #2
x=0.416
y=0.495
z=-1.714
visibility=0.9989696741104126
presence=0.9967280626296997
Frame 10 | Landmark #3
x=0.441
y=0.498
z=-1.714
visibility=0.9988699555397034
presence=0.9962955117225647
Frame 10 | Landmark #4
x=0.297
y=0.478
z=-1.863
visibility=0.9989857077598572
presence=0.9969286322593689
Frame 10 | Landmark #5
x=0.259
y=0.471
z=-1.864
visibility=0.998940110206604
presence=0.9967888593673706
Frame 10 | Landmark #6
x=0.219
y=0.465
z=-1.864
visibility=0.9988484382629395
presence=0.9962607026100159
Frame 10 | Landmark #7
x=0.436
y=0.513
z=-0.677
visibility=0.9983626008033752
presence=0.9962038397789001
Frame 10 | Landmark #8
x=0.148
y=0.472
z=-1.386
visibility=0.9988992810249329
presence=0.9956346154212952
Frame 10 | Landmark #9
x=0.374
y=0.583
z=-1.493
visibility=0.9981316328048706
presence=0.9951474070549011
Frame 10 | Landmark #10
x=0.265
y=0.577
z=-1.696
visibility=0.998559296131134
presence=0.9956315755844116
Frame 10 | Landmark #11
x=0.491
y=0.753
z=0.020
visibility=0.984908938407898
presence=0.9754079580307007
Frame 10 | Landmark #12
x=-0.176
y=0.759
z=-1.247
visibility=0.986172080039978
presence=0.9656978845596313
Frame 11 | Landmark #0
x=0.337
y=0.533
z=-1.910
visibility=0.9985939860343933
presence=0.9923650026321411
Frame 11 | Landmark #1
x=0.377
y=0.487
z=-1.721
visibility=0.998792827129364
presence=0.993205189704895
Frame 11 | Landmark #2
x=0.406
y=0.490
z=-1.721
visibility=0.9987812042236328
presence=0.9930229187011719
Frame 11 | Landmark #3
x=0.432
y=0.493
z=-1.721
visibility=0.9987005591392517
presence=0.9924076199531555
Frame 11 | Landmark #4
x=0.286
y=0.474
z=-1.877
visibility=0.9987120628356934
presence=0.9926188588142395
Frame 11 | Landmark #5
x=0.249
y=0.468
z=-1.878
visibility=0.9986472129821777
presence=0.9920221567153931
Frame 11 | Landmark #6
x=0.209
y=0.462
z=-1.877
visibility=0.9985272288322449
presence=0.9906214475631714
Frame 11 | Landmark #7
x=0.429
y=0.508
z=-0.677
visibility=0.9981918334960938
presence=0.9922818541526794
Frame 11 | Landmark #8
x=0.136
y=0.471
z=-1.388
visibility=0.9985739588737488
presence=0.988052487373352
Frame 11 | Landmark #9
x=0.363
y=0.580
z=-1.501
visibility=0.997940719127655
presence=0.9842175245285034
Frame 11 | Landmark #10
x=0.254
y=0.574
z=-1.711
visibility=0.998267412185669
presence=0.9831370711326599
Frame 11 | Landmark #11
x=0.487
y=0.751
z=0.049
visibility=0.9850615859031677
presence=0.9310077428817749
Frame 11 | Landmark #12
x=-0.192
y=0.761
z=-1.251
visibility=0.9848506450653076
presence=0.8719180822372437
Frame 12 | Landmark #0
x=0.325
y=0.527
z=-1.935
visibility=0.998496413230896
presence=0.9943311214447021
Frame 12 | Landmark #1
x=0.364
y=0.480
z=-1.740
visibility=0.9987289905548096
presence=0.9947985410690308
Frame 12 | Landmark #2
x=0.393
y=0.483
z=-1.739
visibility=0.9987285733222961
presence=0.9946925044059753
Frame 12 | Landmark #3
x=0.421
y=0.486
z=-1.739
visibility=0.9986611008644104
presence=0.9942666888237
Frame 12 | Landmark #4
x=0.273
y=0.468
z=-1.895
visibility=0.9986079931259155
presence=0.9942545294761658
Frame 12 | Landmark #5
x=0.237
y=0.463
z=-1.896
visibility=0.9985281229019165
presence=0.9937601685523987
Frame 12 | Landmark #6
x=0.196
y=0.457
z=-1.896
visibility=0.9983961582183838
presence=0.992609441280365
Frame 12 | Landmark #7
x=0.420
y=0.501
z=-0.679
visibility=0.9981663227081299
presence=0.9942898750305176
Frame 12 | Landmark #8
x=0.122
y=0.467
z=-1.385
visibility=0.9984439015388489
presence=0.9908460974693298
Frame 12 | Landmark #9
x=0.352
y=0.575
z=-1.524
visibility=0.997940182685852
presence=0.9895521998405457
Frame 12 | Landmark #10
x=0.244
y=0.570
z=-1.733
visibility=0.9981910586357117
presence=0.9884588122367859
Frame 12 | Landmark #11
x=0.488
y=0.750
z=0.046
visibility=0.9856202602386475
presence=0.9438676834106445
Frame 12 | Landmark #12
x=-0.207
y=0.763
z=-1.253
visibility=0.9842913150787354
presence=0.8988133668899536
Frame 13 | Landmark #0
x=0.311
y=0.517
z=-2.069
visibility=0.9985253214836121
presence=0.9964141845703125
Frame 13 | Landmark #1
x=0.352
y=0.468
z=-1.877
visibility=0.9987632036209106
presence=0.9964197874069214
Frame 13 | Landmark #2
x=0.382
y=0.470
z=-1.877
visibility=0.9987648129463196
presence=0.9961695075035095
Frame 13 | Landmark #3
x=0.412
y=0.472
z=-1.876
visibility=0.9987024664878845
presence=0.9956943988800049
Frame 13 | Landmark #4
x=0.259
y=0.457
z=-2.009
visibility=0.9986441731452942
presence=0.9964622855186462
Frame 13 | Landmark #5
x=0.221
y=0.451
z=-2.010
visibility=0.9985620975494385
presence=0.9963080883026123
Frame 13 | Landmark #6
x=0.180
y=0.447
z=-2.010
visibility=0.9984411001205444
presence=0.9957906603813171
Frame 13 | Landmark #7
x=0.417
y=0.490
z=-0.811
visibility=0.9982333779335022
presence=0.9955958724021912
Frame 13 | Landmark #8
x=0.105
y=0.456
z=-1.412
visibility=0.9984933733940125
presence=0.9953858256340027
Frame 13 | Landmark #9
x=0.344
y=0.566
z=-1.660
visibility=0.998031735420227
presence=0.9931771755218506
Frame 13 | Landmark #10
x=0.233
y=0.561
z=-1.837
visibility=0.9982564449310303
presence=0.9935949444770813
Frame 13 | Landmark #11
x=0.499
y=0.749
z=-0.115
visibility=0.9862340092658997
presence=0.9428427815437317
Frame 13 | Landmark #12
x=-0.216
y=0.763
z=-1.237
visibility=0.9846394062042236
presence=0.9429135918617249
Frame 14 | Landmark #0
x=0.309
y=0.518
z=-2.042
visibility=0.9982988238334656
presence=0.9886506795883179
Frame 14 | Landmark #1
x=0.352
y=0.467
z=-1.841
visibility=0.9986603856086731
presence=0.9905346035957336
Frame 14 | Landmark #2
x=0.382
y=0.470
z=-1.841
visibility=0.9986696839332581
presence=0.9906314611434937
Frame 14 | Landmark #3
x=0.412
y=0.472
z=-1.841
visibility=0.9986153244972229
presence=0.9899853467941284
Frame 14 | Landmark #4
x=0.259
y=0.457
z=-1.991
visibility=0.9984326362609863

In [71]:
df = pd.DataFrame(extracted_data)
df

,frame,part,part_idx,x,y,z,visibility,presence
0,0,head,0,0.060344,-0.604137,-0.257586,0.999154,0.999230
1,0,left shoulder,11,0.105495,-0.448331,-0.045455,0.987015,0.956319
2,0,right shoulder,12,-0.149624,-0.435491,-0.159053,0.990897,0.977459
3,0,left elbow,13,0.087928,-0.321413,-0.047882,0.177682,0.066476
4,0,right elbow,14,-0.158428,-0.195147,-0.153220,0.179995,0.015819
...,...,...,...,...,...,...,...,...
2166,181,right hip,24,-0.096994,0.004038,-0.055607,0.013594,0.000158
2167,181,left knee,25,0.129641,-0.123378,-0.008920,0.016743,0.000142
2168,181,right knee,26,-0.093834,0.009469,-0.173397,0.046887,0.000198
2169,181,left ankle,27,0.131347,0.150201,0.257683,0.006132,0.000080
2170,181,right ankle,28,-0.152946,0.377084,0.150331,0.017059,0.000151

### Xu Ly data balance

In [72]:
df_balance = df[df['part'].isin(['left hip', 'right hip', 'left shoulder', 'right shoulder'])]
df_balance.to_csv('balance_data.csv', index=False)
df_balance

,frame,part,part_idx,x,y,z,visibility,presence
1,0,left shoulder,11,0.105495,-0.448331,-0.045455,0.987015,0.956319
2,0,right shoulder,12,-0.149624,-0.435491,-0.159053,0.990897,0.977459
7,0,left hip,23,0.098934,-0.003050,0.062111,0.001587,0.000279
8,0,right hip,24,-0.096827,-0.007484,-0.058086,0.001987,0.000335
14,1,left shoulder,11,0.105648,-0.448475,-0.042521,0.987811,0.984075
...,...,...,...,...,...,...,...,...
2153,180,right hip,24,-0.096935,0.003585,-0.056110,0.014911,0.000166
2159,181,left shoulder,11,0.109122,-0.456020,-0.036441,0.991785,0.985711
2160,181,right shoulder,12,-0.163564,-0.438993,-0.167508,0.996505,0.994993
2165,181,left hip,23,0.097829,-0.014296,0.058917,0.013105,0.000112
2166,181,right hip,24,-0.096994,0.004038,-0.055607,0.013594,0.000158

In [73]:
df_balance_pivot = df_balance.pivot(index='frame', columns='part', values=['x', 'y', 'z'])
df_balance_pivot.columns = [f"{axis}_{part.replace(' ', '_')}" for axis, part in df_balance_pivot.columns]
df_balance_pivot = df_balance_pivot.reset_index()
#df_balance_pivot

In [74]:
shoulder_width_raw = np.sqrt((df_balance_pivot['x_left_shoulder'] - df_balance_pivot['x_right_shoulder'])**2 + (df_balance_pivot['y_left_shoulder'] - df_balance_pivot['y_right_shoulder'])**2 + (df_balance_pivot['z_left_shoulder'] - df_balance_pivot['z_right_shoulder'])**2)
shoulder_width = shoulder_width_raw.mean()
print(shoulder_width)

0.26302747731062087

# Tinh sway index

In [75]:
df_balance_pivot['com_x'] = (df_balance_pivot['x_left_hip'] + df_balance_pivot['x_right_hip'] ) / 2
df_balance_pivot['com_y'] = (df_balance_pivot['y_left_hip'] + df_balance_pivot['y_right_hip'] ) / 2
df_balance_pivot['com_z'] = (df_balance_pivot['z_left_hip'] + df_balance_pivot['z_right_hip'] ) / 2
df_balance_pivot['std_com_x'] = df_balance_pivot['com_x']/shoulder_width
df_balance_pivot['std_com_y'] = df_balance_pivot['com_y']/shoulder_width
df_balance_pivot['std_com_z'] = df_balance_pivot['com_z']/shoulder_width
window_size = 30
sway_x = df_balance_pivot['std_com_x'].rolling(window=window_size).std()
sway_y = df_balance_pivot['std_com_y'].rolling(window=window_size).std()
sway_z = df_balance_pivot['std_com_z'].rolling(window=window_size).std()
df_balance_pivot['sway_index'] = np.sqrt(sway_x**2 + sway_y**2 + sway_z**2).fillna(0)
#print(df_balance_pivot[['frame', 'std_com_x', 'std_com_y', 'std_com_z', 'sway_index']])

# Tinh Posture Deviation

In [76]:
mid_shoulder_x = (df_balance_pivot['x_left_shoulder'] + df_balance_pivot['x_right_shoulder']) / 2
mid_shoulder_y = (df_balance_pivot['y_left_shoulder'] + df_balance_pivot['y_right_shoulder']) / 2
mid_shoulder_z = (df_balance_pivot['z_left_shoulder'] + df_balance_pivot['z_right_shoulder']) / 2
v_x = df_balance_pivot['com_x'] - mid_shoulder_x
v_y = df_balance_pivot['com_y'] - mid_shoulder_y
v_z = df_balance_pivot['com_z'] - mid_shoulder_z
length_v = np.sqrt(v_x**2 + v_y**2 + v_z**2)
cos = v_y / length_v
cos = np.clip(cos, -1, 1)
df_balance_pivot['Posture_Deviatation'] = np.degrees(np.arccos(cos))

# Tinh CoM Movement

In [77]:
anchor_x = df_balance_pivot['std_com_x'].iloc[window_size].mean()
anchor_y = df_balance_pivot['std_com_y'].iloc[window_size].mean()
anchor_z = df_balance_pivot['std_com_z'].iloc[window_size].mean()
df_balance_pivot["CoM_Distance"] = np.sqrt((df_balance_pivot['std_com_x'] - anchor_x)**2 + (df_balance_pivot['std_com_y'] - anchor_y)**2 + (df_balance_pivot['std_com_z'] - anchor_z)**2)
df_balance_statistics = df_balance_pivot[['frame', 'sway_index', 'Posture_Deviatation', 'CoM_Distance']]
df_balance_statistics.to_csv('balance_statistics.csv', index=False)